python: 
 - "2.7"
virtualenv:
  system_site_packages: true
language: python
before_install: 
 - sudo apt-get install software-properties-common
 - sudo add-apt-repository -y ppa:gijzelaar/aartfaac
 - sudo apt-get update -qq
 - sudo apt-get install -qq pyrap
script: 
 - dpkg -l | grep pyrap
 - python -c "import pyrap; print pyrap.__file__"
 - python -c "import pyrap.measures; print pyrap.measures.__file__"
